name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/linux-pc/Deployed-REST-API-Clean-Arch
            git pull origin main
            docker stop deployed-rest-api-clean-arch-container
            docker rm deployed-rest-api-clean-arch-container
            docker rmi deployed-rest-api-clean-arch
            docker build -t deployed-rest-api-clean-arch:latest .
            docker run -d -p 80:80 -e JWT_KEY=${{ secrets.JWT_KEY }} -e DBUSER=${{ secrets.DBUSER }} -e DBPASS=${{ secrets.DBPASS }} -e DBHOST=${{ secrets.DBHOST }} -e DBPORT=${{ secrets.DBPORT }} -e DBNAME=${{ secrets.DBNAME }} --name deployed-rest-api-clean-arch-container deployed-rest-api-clean-arch:latest
